// Generated by CoffeeScript 1.6.3
(function() {
  var apiKey, recognition, transcript, translate;

  recognition = new webkitSpeechRecognition();

  recognition.continuous = true;

  recognition.interminResults = true;

  apiKey = 'AIzaSyDUpThQIyJRlszXEnT2HvSMbPbObbcYNE4';

  translate = function(text, language) {
    return $.get("https://www.googleapis.com/language/translate/v2?key=" + apiKey + "&q=" + text + "&target=" + language, function(data) {
      var msg, translatedText;
      translatedText = data.data.translations[0].translatedText;
      $('#output').text(translatedText);
      msg = new SpeechSynthesisUtterance(translatedText);
      msg.lang = 'fr-FR';
      return window.speechSynthesis.speak(msg);
    });
  };

  transcript = '';

  recognition.onstart = function() {
    return recognition.lang = 'English';
  };

  recognition.onresult = function(event) {
    var result, _i, _len, _ref;
    transcript = '';
    _ref = event.results;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      result = _ref[_i];
      transcript += result[0].transcript;
    }
    $('#input').text(transcript);
    return translate(transcript, 'fr');
  };

  recognition.onerror = function() {};

  recognition.onend = function() {};

  recognition.start();

}).call(this);
