// Generated by CoffeeScript 1.6.3
(function() {
  var Message, apiKey;

  apiKey = 'AIzaSyDUpThQIyJRlszXEnT2HvSMbPbObbcYNE4';

  window.initSpeechRecognition = function(language, onresult) {
    var recognition;
    recognition = new webkitSpeechRecognition();
    recognition.continuous = true;
    recognition.interminResults = false;
    recognition.onstart = function() {
      return recognition.lang = language;
    };
    recognition.onresult = onresult;
    recognition.onerror = function(err) {
      return console.error(err);
    };
    recognition.onend = function() {};
    recognition.start();
    return recognition;
  };

  Message = (function() {
    function Message(sender, text, language) {
      this.sender = sender;
      this.text = text;
      this.language = language;
    }

    Message.messages = [];

    Message.prototype.save = function() {
      Message.messages.push(this);
      return gapi.hangout.data.sendMessage(JSON.stringify(this));
    };

    Message.all = function() {
      return Message.messages;
    };

    Message.save = function(message) {
      return this.messages.push(message);
    };

    Message.speak = function(message) {
      var msg;
      msg = new SpeechSynthesisUtterance();
      msg.text = message.text;
      msg.lang = message.language;
      return window.speechSynthesis.speak(msg);
    };

    Message.translate = function(message, targetLanguage, callback) {
      if (message.language === targetLanguage) {
        return callback(message);
      }
      return $.getJSON("https://www.googleapis.com/language/translate/v2?key=" + apiKey + "&q=" + message.text + "&source=" + message.language + "&target=" + targetLanguage, function(data) {
        return callback(new Message(message.sender, data.data.translations[0].translatedText, targetLanguage));
      });
    };

    return Message;

  })();

  window.Message = Message;

}).call(this);
