// Generated by CoffeeScript 1.6.3
(function() {
  var Message, apiKey, initSpeechRecognition;

  apiKey = 'AIzaSyDUpThQIyJRlszXEnT2HvSMbPbObbcYNE4';

  initSpeechRecognition = function(language, onresult) {
    var recognition;
    recognition = new webkitSpeechRecognition();
    recognition.continuous = true;
    recognition.interminResults = false;
    recognition.onstart = function() {
      return recognition.lang = language;
    };
    recognition.onresult = onresult;
    recognition.onerror = function(err) {
      return console.error(err);
    };
    recognition.onend = function() {};
    recognition.start();
    return recognition;
  };

  Message = (function() {
    function Message(speaker, text, language) {
      this.speaker = speaker;
      this.text = text;
      this.language = language;
    }

    Message.speak = function(message) {
      var msg;
      msg = new SpeechSynthesisUtterance();
      msg.text = message.text;
      msg.lang = message.language;
      return window.speechSynthesis.speak(msg);
    };

    Message.translate = function(message, targetLanguage, callback) {
      if (message.language === targetLanguage) {
        return callback(message);
      }
      return $.getJSON("https://www.googleapis.com/language/translate/v2?key=" + apiKey + "&q=" + message.text + "&source=" + message.language + "&target=" + targetLanguage, function(data) {
        return callback(new Message(message.speaker, data.data.translations[0].translatedText, targetLanguage));
      });
    };

    return Message;

  })();

}).call(this);
